
server:
  port: 8082
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_
  configuration:
    map-underscore-to-camel-case: false
spring:
  datasource:
    url: jdbc:mysql://192.168.12.52:3306/1906b?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 100
      max-active: 1000
      min-idle: 5
      max-wait: 60000
mail:
  from: 389168944@qq.com
  password: yhwpqpuyqtiybhdd
  host: smtp.qq.com
  protocol: smtp

stock:
  count: 10